/*
 * ATMClient.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;

import javax.swing.JFrame;

import com.ATMClientService;

import util.Constant;
import util.Util;

/**
 *
 * @author  __USER__
 */
public class ATMClient extends javax.swing.JFrame {
	static ATMClientService atmClientService = new ATMClientService();

	/** Creates new form ATMClient */
	public ATMClient() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 335,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 353,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		//初始化账户列表
		//Util.ReadFileAccount();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Constant.ATMCLIENTSERVICE = atmClientService;
				ATMClient atmClient = new ATMClient();
				atmClient.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				atmClient.setVisible(true);
				atmClient.setLayout(null);
				MainPanel mainPanel = new MainPanel(atmClient);
				//将当前显示的panel加入到列表中
				Constant.JPANELLIST.add(mainPanel);
				atmClient.setLayout(new FlowLayout(FlowLayout.CENTER));
				atmClient.add(mainPanel);

			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}