/*
 * LoginPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import java.awt.FlowLayout;

import javax.swing.JPanel;

import util.Constant;

import com.ATMClientService;
import com.Bank;
import com.To;


import entity.Account;
import entity.SavingAccount;
import exception.LoginException;

/**
 *
 * @author  __USER__
 */
public class LoginPanel extends javax.swing.JPanel {
	ATMClient atmClient;

	/** Creates new form LoginPanel */
	public LoginPanel(ATMClient atmClient) {
		this.atmClient = atmClient;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		jLabel1.setText("\u7528\u6237\u8d26\u53f7\uff1a");

		jLabel2.setText("\u7528\u6237\u5bc6\u7801\uff1a");

		jButton1.setText("\u786e\u8ba4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(75, Short.MAX_VALUE)
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												layout.createSequentialGroup()
														.add(jButton1)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.UNRELATED)
														.add(jButton2)
														.add(55, 55, 55))
										.add(layout
												.createSequentialGroup()
												.add(jLabel2)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jTextField2,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														163, Short.MAX_VALUE))
										.add(layout
												.createSequentialGroup()
												.add(jLabel1)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jTextField1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														163,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.add(64, 64, 64)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(60, 60, 60)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel1)
								.add(jTextField1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.add(59, 59, 59)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel2)
								.add(jTextField2,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED, 47,
								Short.MAX_VALUE)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jButton2).add(jButton1)).add(41, 41, 41)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//跳回最初的界面
		MainPanel businessPanel = new MainPanel(atmClient);
		for (JPanel jp : Constant.JPANELLIST) {
			atmClient.remove(jp);
		}
		//atmClient.remove(Constant.JPANELLIST.get(0));
		Constant.JPANELLIST.add(businessPanel);
		atmClient.add(businessPanel, new FlowLayout(FlowLayout.CENTER));
		//atmClient.repaint();
		atmClient.validate();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		long id = Long.parseLong(jTextField1.getText());
		String password = jTextField2.getText();
		//Bank bank = Bank.getInstance();
		try {
			//Account account = bank.login(id, password);
			Account account = new SavingAccount();
			account.setId(id);
			account.setPassword(password);
			To to = new To();
			to.setMyAccount(account);
			to.setAction("login");
			account.toString();
			if(Constant.ATMCLIENTSERVICE.sendMsg(to)){
				to = Constant.ATMCLIENTSERVICE.receiveMsg();
				BusinessPanel businessPanel = new BusinessPanel(atmClient, to.getMyAccount());
				for (JPanel jp : Constant.JPANELLIST) {
					atmClient.remove(jp);
				}
				//atmClient.remove(Constant.JPANELLIST.get(0));
				Constant.JPANELLIST.add(businessPanel);
				atmClient.add(businessPanel, new FlowLayout(FlowLayout.CENTER));
				//atmClient.repaint();
				atmClient.validate();
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}